### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by GameTec-live** [RfidResearchGroup/ChameleonUltra#11]
Consider adding a license to this project, in my opinion a GPL V3 or something similar would fit just fine.

(How do i come to GPL V3? a) I like the GPL V3 b) the Proxmark and some other repos are already licensed under GPL V3, so why not this one?)

**Comment by xianglin1998** [comment]
The Chameleon Ultra uses some code from Proxmark3 RRG Repo, perhaps we should continue the license statement from Proxmark3 RRG Repo.

**Comment by GameTec-live** [comment]
wouldnt the gpl v3 (under which the pm3 repo is licensed?) require the licensing under gplv3 if parts of that code is used?
also: does indeed make sense

**Comment by xianglin1998** [comment]
I am not familiar with GPL V3, which may require ICEMAN's help.

**Comment by GameTec-live** [comment]
from my understanding, if you use part of GPL licensed code, the project this licensed code is in must also be licensed under the same GPL version? (eg GPL V3)

**Comment by GameTec-live** [comment]
<img width="774" alt="image" src="https://github.com/RfidResearchGroup/ChameleonUltra/assets/66077766/51992386-2be3-4308-bc18-a07c62b4001d">
github even has a neat summery XD

**Comment by xianglin1998** [comment]
Yes, GPLV3 is inheritance. Our project should be GPLV3 or more strictly licensed, but I think GPLV3 should be enough. A good project cannot be separated from more people/groups that create value for themselves or others, sure, must following GPLV3.

**Comment by xianglin1998** [comment]
The project start follow GPLV3.
Look commit: a048187
