### ISSUE TITLE
Mifare 1k emulation problem

### ISSUE THREAD

**Issue by mitmarcus** [RfidResearchGroup/ChameleonUltra#111]
Keyfob Im trying to copy is a "NXP MIFARE"

The reader is a Salto Modular XS - EU Wall Reader

Card is successfully read and the keys are aqquired, however upon emulation the reader always denies the chameleon. Running mfkey32 results in keys that are always "FFFFFFFFFFFF".

I have the binary dump, but can't upload it here. Am I missing something to emulate it?

**Comment by the0ne944** [comment]
> Keyfob Im trying to copy is a "NXP MIFARE"
> 
> The reader is a Salto Modular XS - EU Wall Reader
> 
> Card is successfully read and the keys are aqquired, however upon emulation the reader always denies the chameleon. Running mfkey32 results in keys that are always "FFFFFFFFFFFF".
> 
> I have the binary dump, but can't upload it here. Am I missing something to emulate it?

No, there is a firmware problem your re Right 

> Keyfob Im trying to copy is a "NXP MIFARE"
> 
> The reader is a Salto Modular XS - EU Wall Reader
> 
> Card is successfully read and the keys are aqquired, however upon emulation the reader always denies the chameleon. Running mfkey32 results in keys that are always "FFFFFFFFFFFF".
> 
> I have the binary dump, but can't upload it here. Am I missing something to emulate it?

Hi we have all the same problem refer: https://github.com/RfidResearchGroup/ChameleonUltra/issues/110

**Comment by doegox** [comment]
This is very probably the same as #110 so I will close this one as duplicate and invite you to discuss it on the other issue, thank you!
