### ISSUE TITLE
Add Github Pages deployment for docs

### ISSUE THREAD

**Issue by GameTec-live** [RfidResearchGroup/ChameleonUltra#128]
As this repository already owns the chameleonultra.com domain it might be useful to enable a github pages deployment and point it to the docs folder. 

<img width="409" alt="image" src="https://github.com/RfidResearchGroup/ChameleonUltra/assets/66077766/6bac9c20-b5e0-4fe7-bea9-ea1fea196ffb">

This would automatically set up a Markdown web builder. One could then link this markdown web builder to a subdomain (like docs.chameleonultra.com) by creating a CNAME file and have a quick and short link to web docs.

Benefits:
No practical ones, but its pretty, a short link and its "cleaner" without all of the github interface. It might also load faster, but that doesnt really matter, does it? + Its literally free...

**Comment by xianglin1998** [comment]
Good idea, try it.

**Comment by xianglin1998** [comment]
Finish, document link to here:
https://chameleonultra.com/docs
