### ISSUE TITLE
LF scan/read issues

### ISSUE THREAD

**Issue by Barishhh** [RfidResearchGroup/ChameleonUltra#133]
I can't seem to scan my LF tag properly using the CLI and the GUI app. The GUI recognized the EM4100 tag, except when saving it it's exporting a 0kb file. 

Am I doing something wrong or is this a bug?

**Comment by Foxushka** [comment]
You are reporting GUI "bug" on wrong repo. You should report this to https://github.com/GameTec-live/ChameleonUltraGUI. 

But no, this isn't bug if you are trying to save .bin from EM4100, as .bin is only for Mifare Classic (EM4100 doesn't have any internal data, only UID). If you will export .json it will be fine

**Comment by Barishhh** [comment]
My bad. Thanks for your fast reply!
