### ISSUE TITLE
Upgrade the firmware into a brick

### ISSUE THREAD

**Issue by Lw-AI** [RfidResearchGroup/ChameleonUltra#136]
Upgrade the chameleon through the latest computer-side GUI, after the download is completed, the two green lights in the middle of the chameleon began to flash for half an hour, and then I removed the chameleon, and pressing the B button will light up the two red lights in the middle,The computer can detect it and display UFD mode. Is there any hope for recovery?

**Comment by hank9999** [comment]
follow the process in [docs/firmware](https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/docs/firmware.md) to flash your chameleon with nrfutil

**Comment by qingyifeihu** [comment]
Well, thanks, the problem has been solved
