### ISSUE TITLE
Mfc 1k full emulation issue with an OEM terminal

### ISSUE THREAD

**Issue by spp2000** [RfidResearchGroup/ChameleonUltra#144]
An OEM access control system, in addition to simply controlling access, also allows you to perform a series of operations from the terminal (queries, etc.). To do this, the tag must be left on the reader in order to keep the session open.

Analyzing 3 traces I noticed that, after the first authentication, the system waits for instructions by executing a loop of two `READBLOCK`: it continuously asks for `AUTH-B(12)` - `READBLOCK(12)` - `READBLOCK(13)` (see pictures).

With Ultra (latest fw) the initial authentication works fine but, during the wait/loops, every 2 seconds (more or less) the communication stops and starts again from the beginning, therefore prevents me from continuing with the next operations.

For the 3 traces acquired we observe that:
- after 3 loops, _fdt_ after `AUTH-B(12)` is shorter than the previous (about 1600 Vs 3000) -> collision?
- after 225 or 230 loops (about 2 seconds), _fdt_ after `READBLOCK (13)` are shorter than the previous (about 1600 Vs 5200) -> collision?
Then we have a new ANTICOLL, etc... 

I can't acquire more time with pm3, but from the terminal I see that this behavior repeats continuously after about 2 seconds.

Given that this behavior does not seem exactly systematic, I will try to take other traces to have a minimum of statistics on this behavior, if it can be useful.
Thank you
traceman ;)

**Trace n.1**

![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/42212032/ffa81f48-1550-4c49-8421-95566bca1129)

**Trace n.2**

![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/42212032/cf17a789-9931-4c47-8c11-36aecd5f8831)

**Trace n.3**

![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/42212032/3d45fa6c-c665-417e-9ae8-a5da4f2e6a20)

**Comment by mitmarcus** [comment]
can confirm there's still an issue 


https://github.com/RfidResearchGroup/ChameleonUltra/assets/114725463/ff0c4722-ba84-4b41-85f7-ac942d792f5f

**Comment by spp2000** [comment]
I took more than 10 traces and I can confirm that, in my case, the communication restarts **always and only** after those commands during the waiting loops. fdt is **always** about 1600 when the issue occurs, but there is no rule as to when this happens: it can happen after 2, 30, 50, 70, 200 loops indifferently.

**Comment by spp2000** [comment]
**Ultra Vs Rev.G**
Rev.G fdt never drops (like Ultra in the pictures above) and are much longer

![Ultra](https://github.com/RfidResearchGroup/ChameleonUltra/assets/42212032/641150db-59b0-4958-96d6-b27ae3ab12e3)


![RevG](https://github.com/RfidResearchGroup/ChameleonUltra/assets/42212032/79871ad8-ca3c-4e60-b74c-43df57822a1a)

**Comment by mitmarcus** [comment]
With 2.0 it seems to work
@spp2000 can you check on your readers?

**Comment by mitmarcus** [comment]
aaaand it's broken again

**Comment by spp2000** [comment]
For me nothing has changed since the last time the emulation was improved.  The readers that worked continue to work, while the one that was ko remained ko.
What problem do you experience?

**Comment by mitmarcus** [comment]
remember my "problematic" Salto modular XS reader?
with the original V2 (2 weeks ago) it was working without issue.
I have updated today to the latest and reader won't work again with it.

really no idea what the issue might be.

**Comment by xianglin1998** [comment]
@mitmarcus After tracing with SPP2000, we have finally resolved two bugs that affect the simulation of 14a and mf1. You can update to the latest build version to test whether they have solved your problem at the same time. I think this is a high probability.
