### ISSUE TITLE
Chameleon Lite HW issues

### ISSUE THREAD

**Issue by Lostish** [RfidResearchGroup/ChameleonUltra#145]
Hi,

Dont know where to turn. And if this is the right way. If not, please direct me to where i can get help with this.

Supported the indiegogo campaing and received the items few weeks ago.
Tested the stuff and done some testing with it.
Now the Chameleon Lite start acting strange.

The same issue with ORIGINAL fw the device ships with from here and latest compiled from master branch.

I had it over night in a pocket and the day after the device does not respond to button press, at all.
Connected to USB it all works as it should, and button press get recognized.
I dont want this to be a tethered device. That defeats the purpuse of it :(

Measured the little yellow battery @ the battery connectios soldered points on the PCB and the batt pad on the back side, charged to 4.17v ( CLI confirms )
No reaction to button presses.
Adding 3.3v to the button, jumping the connection, simulating a button press, it all lights up, and works for a second.

Does any one have a device schematics to share to dig in to the issue?
Or maby share a email address to direct me where i can possibly be sent a new device or some help from proxgrind?

I can shoot video or pictures to verify my issue if needed.

Regards
Kim

**Comment by GameTec-live** [comment]
try emailing dennis (email should be in one of the indigogo status updates)

**Comment by Lostish** [comment]
I emailed him and lets await a solution.

Thanks
