### ISSUE TITLE
[idea]希望完善功能

### ISSUE THREAD

**Issue by lin1414814113** [RfidResearchGroup/ChameleonUltra#161]
之前是用tinypro，，现在这个希望增加之前tinypro的旧功能，第一个：可以批量扫描指定文件夹里面的dump文件，并且自动同步文件名作为卡片名，这样就不用一个一个手动添加。第二个之前开着手机蓝牙打开软件可以自动连接，不用按变色龙按钮，现在还需要按一下变色龙，并且UItra刷卡也更慢，看看能不能改进

**Comment by taichunmin** [comment]
Duplicated with #162
