### ISSUE TITLE
How is the top epoxy cover of Chameleon Super made? Is the mold gluing method used? Send me the 3D file of the glue injection mold. Thank you

### ISSUE THREAD

**Issue by llliii0325** [RfidResearchGroup/ChameleonUltra#179]
Please keep in mind we are still at the infancy of the project and a lot has still to be done.

Have first a look at the [Whitepaper](https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/docs/technical_whitepaper.md), the Wiki [Roadmap](https://github.com/RfidResearchGroup/ChameleonUltra/wiki/Public-Roadmap) and [Wishlist](https://github.com/RfidResearchGroup/ChameleonUltra/wiki/Wishlist).  
No need for creating issues for well known missing supports, we are already aware :)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by doegox** [comment]
learn to open proper issues
