### ISSUE TITLE
The GUI don't save new card

### ISSUE THREAD

**Issue by Tozneno** [RfidResearchGroup/ChameleonUltra#192]
With Android app (1.0.0 build 388), When i want to save a new card i've juste reading, the GUI ask me a name for it then i try to press ok button but nothing append, i could only press annule button.
I can save it to .bin form but not directly in the application. I've tested in bluetooth or cable connexion, but same result.

I precise that the first version of the GUI app i used work right for saving.
My chameleon have the lastest firmware.

**Comment by GameTec-live** [comment]
it works for me. Are you sure it doesn't create a new card under saved cards?

**Comment by Tozneno** [comment]
Nop i try to save with différents name, i also reset my chameleon ultra for re testing.
No New card added 🙁

**Comment by GameTec-live** [comment]
what about some more info like os, etc

**Comment by Tozneno** [comment]
Ok for now i try first Time to un install and reinstall the app, same problem.
But i try to delete app data storage in Android app manager, and it works again now.
Very strange...
When i re install the app it say to me some permission problem. Let see with a pict
![Screenshot_20231226_094631](https://github.com/RfidResearchGroup/ChameleonUltra/assets/154840290/e1757a49-46bb-42e3-83e0-96efda98fc8c)

**Comment by GameTec-live** [comment]
did you forget to grant it the permissions required for bluetooth?

**Comment by Tozneno** [comment]
I grant every permissions the gui app Ask me.
The error message don't ocure anymore After this single appear.
For resuming some wizardery append but for now everything is ok again with the gui app.

**Comment by GameTec-live** [comment]
? so everything works now or?

**Comment by Tozneno** [comment]
Yep 👍

**Comment by GameTec-live** [comment]
mind closing this issue then?

**Comment by Elinas-of-Alba** [comment]
No, have the same issue on Mac OS GUI and iOS. If I want to save the card it does simply nothing.
