### ISSUE TITLE
My equipment is not working for some reason

### ISSUE THREAD

**Issue by xie19960101** [RfidResearchGroup/ChameleonUltra#195]
![Uploading IMG_8451.jp

https://github.com/RfidResearchGroup/ChameleonUltra/assets/155366221/5478f9da-e4ef-49e6-9fcb-e88a3d19b276

eg…]()

**Comment by SomeBoneHead** [comment]
I'm not part of the project but rather an end user like you, that said.

Most people here would be happy to help you but since you haven't listed any troubleshooting you have done or if it just stoped working, if it never worked, if something happened before it stopped working, if it never worked where you got it from, ECT.

We'd need information to help you.

**Comment by panayotoff** [comment]
Does it work when plugged to USB? I have Devboard that's working only when plugged to the USB. The battery is OK, power is going in through the terminals ( I even purchased same  brand new battery - no luck ).

Try plugging it into USB and see if it works this way.

**Comment by xie19960101** [comment]
![3a32bf1a0cecb0ba7dded8a5b94e22f](https://github.com/RfidResearchGroup/ChameleonUltra/assets/155366221/f50b9919-0796-40d6-acf2-26d94be89c6b)
<img width="949" alt="c06b3842bfe775b6015a557ec832c55" src="https://github.com/RfidResearchGroup/ChameleonUltra/assets/155366221/5aa3229f-8f7e-4109-961c-3ee4110fc5cc">

**Comment by xie19960101** [comment]
I haven't used it since it broke. Today I tried my Ultra to Lite with my computer，Unable to enter debug mode, unable to brush firmware

**Comment by xie19960101** [comment]
> 也就是说，我不是项目的一部分，而是像你一样的最终用户。
> 
> 这里的大多数人都很乐意帮助您，但是由于您没有列出您所做的任何故障排除，或者它是否停止工作，如果它从未工作过，如果在它停止工作之前发生了某些事情，如果它从未工作过，那么您从哪里得到它，ECT。
> 
> 我们需要信息来帮助您。

I have not been to the forum for a long time and I am very sorry for not replying to you in time. I will explain the problem below

**Comment by xie19960101** [comment]
> 插入 USB 时可以工作吗？我有Devboard，它只有在插入USB时才能工作。电池没问题，电源通过端子进入（我什至购买了相同的全新电池 - 没有运气）。
> 
> 尝试将其插入 USB，看看它是否以这种方式工作。
The USB module responds after being inserted, but cannot be used

**Comment by unknown10777** [comment]
你貌似把 Lite 固件刷到了 Ultra 硬件里，你可以尝试遵循以下文档来进入 DFU 刷入最新的 Ultra 固件。

You seems have flashed a Lite firmware to Ultra hardware.

https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/docs/firmware.md

You can try follow this document and flash a latest Ultra firmware.

**Comment by xie19960101** [comment]
> 你貌似把 Lite 固件刷到了 Ultra 硬件里，你可以尝试遵循以下文档来进入 DFU 刷入最新的 Ultra 固件。
> 
> 您似乎已将 Lite 固件刷新到 Ultra 硬件。
> 
> https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/docs/firmware.md
> 
> 您可以尝试按照本文档刷新最新的 Ultra 固件。

I'm sorry, I've read the documentation carefully and watched many tutorials, but I still don't understand how to use DFU

**Comment by xie19960101** [comment]
Uploading cb23e46ff1afbb562ef795cf4f193ce5.mp4…

**Comment by unknown10777** [comment]
~~第一步，把你的网页翻译关掉；~~
第二步，等设备灯灭后按住B键插入电脑，期间等待15秒不要松手。三秒内设备会闪烁两个绿色灯；
第三步，下载并安装 [nRFUtil](https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-windows/nrfutil.exe) 工具；
第四步，按 win+x 选择 Powershell 管理员；
第五步，输入 `cd ‘C:\’` 并回车，注意区分半角和全角；
第六步，输入 `nrfutil install device` 回车；
第七步，下载 [ultra-dfu-app.zip](https://github.com/RfidResearchGroup/ChameleonUltra/releases/download/dev/ultra-dfu-app.zip)  并放到C盘根目录；
第八步，输入 `nrfutil device program --firmware ultra-dfu-app.zip --traits nordicDfu`并回车，设备会闪烁两个蓝色灯，稍等片刻灯会停止闪烁并且全灭。拔下USB线，同时按下AB键即可唤醒；

**Comment by xie19960101** [comment]
> ~第一步，把你的网页翻译关掉;~ 第二步，等设备灯灭后按住B键插入电脑，期间等待15秒不要松手。三秒内设备会闪烁两个绿色灯; 第三步，下载并安装 [nRFUtil](https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-windows/nrfutil.exe) 工具; 第四步，按 win+x 选择 Powershell 管理员; 第五步，输入 并回车，注意区分半角和全角; 第六步，输入 回车; 第七步，下载 [ultra-dfu-app.zip](https://github.com/RfidResearchGroup/ChameleonUltra/releases/download/dev/ultra-dfu-app.zip) 并放到C盘根目录; 第八步，输入 并回车，设备会闪烁两个蓝色灯，稍等片刻灯会停止闪烁并且全灭。拔下USB线，同时按下AB键即可唤醒;`cd ‘C:\’``nrfutil install device``nrfutil device program --firmware ultra-dfu-app.zip --traits nordicDfu`

兄弟，我根据你教我的步骤一步一步操作，我整理了一个小时可惜毫无进展，总是报错可能是我比较笨拙，DFU软件一直闪退无法安装，你能否选一个合适的时间帮助我远程操作，十分感谢
<img width="876" alt="8bc304efa4490211610c6a90447ebb3" src="https://github.com/RfidResearchGroup/ChameleonUltra/assets/155366221/c894da64-3947-43a0-b1b6-a5b90e4bbaad">
