### ISSUE TITLE
CI must block breaking PRs

### ISSUE THREAD

**Issue by doegox** [RfidResearchGroup/ChameleonUltra#30]
current main branch (e7264bddaaa28ceddeb48cea3e43d3a1a22a8607) is broken because of NTAG PR.
we should implement checks in the CI like for pm3, to avoid merging blindly code that does not even compile...

**Comment by xianglin1998** [comment]
Okay, I will pay attention to this issue.

**Comment by xianglin1998** [comment]
It seems that the current CI is not working properly

**Comment by F9Alejandro** [comment]
Could always have the PR go into its own branch? That way it shouldn't mess with the main branch and CI shouldn't get confused.

**Comment by doegox** [comment]
Tentative have been setup but it breaks setting the builder because of some permission issues, cf https://github.com/RfidResearchGroup/ChameleonUltra/pull/70

**Comment by doegox** [comment]
done
