### ISSUE TITLE
Add command to get battery information

### ISSUE THREAD

**Issue by nieldk** [RfidResearchGroup/ChameleonUltra#38]
https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/firmware/application/src/app_cmd.c needs a definition to DATA_CMD_GET_BATT_INFO in order to enable application to retrieve current battery information.

**Comment by xianglin1998** [comment]
Implemented now(low battery level is 100 to test notice, ignore that.).
![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/23152044/a5435598-b121-4026-b3c3-41450ea15477)

**Comment by xianglin1998** [comment]
This feature has been implemented. If you have any other issues, please open a separate thread.
