### ISSUE TITLE
Chameleon FW can't emulate 7B UID Mifare Classic cards

### ISSUE THREAD

**Issue by the-Jamz** [RfidResearchGroup/ChameleonUltra#47]
Hi, so I'm trying to emulate an EV1 tag (without signature), and I can get the UID/ATQA/SAK to emulate correctly, but then cannot read any data from the tag. I'm using a proxmark3 generic to verify. Any help would be appreciated.

I'm running the latest firmware and using the latest version of the client.

Edit: this now appears to occur with all 7B UID Mifare classic cards.

My steps:
`hw mode set -m e`
`hw slot change -s 1`
`hw slot openall`
`hw slot init -t 3 -s 1`
`hf mf eload -t hex -f dump.eml`
`hf mf sim --sak 08 --atqa 4400 --uid 04**********80` (7 byte uid)

Reading on the proxmark:

Chameleon:
```
[usb] pm3 --> hf 14a info

[+]  UID: 04 ** ** ** ** ** 80
[+] ATQA: 00 44
[+]  SAK: 08 [2]
[+] MANUFACTURER: NXP Semiconductors Germany
[+] Possible types:
[+]    MIFARE Classic 1K CL2
[=] proprietary non iso14443-4 card found, RATS not supported
[+] Prng detection: hard
[#] Auth error
[?] Hint: try `hf mf` commands

[usb] pm3 --> hf mf rdbl --blk 0 -k FFFFFFFFFFFF
[#] Auth error
```

Actual key:
```
[usb] pm3 --> hf 14a info

[+]  UID: 04 ** ** ** ** ** 80
[+] ATQA: 00 44
[+]  SAK: 08 [2]
[+] MANUFACTURER: NXP Semiconductors Germany
[+] Possible types:
[+]    MIFARE Classic 1K CL2
[=] proprietary non iso14443-4 card found, RATS not supported
[+] Prng detection: hard
[=]
[=] --- Tag Signature
(omitted)

[usb] pm3 --> hf mf rdbl --blk 0 -k FFFFFFFFFFFF

[=]   # | sector 00 / 0x00                                | ascii
[=] ----+-------------------------------------------------+-----------------
[=]   0 | 04 ** ** ** ** ** 80 88 44 00 C8 20 00 00 00 00 | ****
```

**Comment by GameTec-live** [comment]
idk if it makes a difference, but maybe try and load a .bin?

**Comment by the-Jamz** [comment]
I've also just tried importing the key dictionary to the GUI, dumping the key using the chameleon, and then loading the card through the GUI, but I get the same result.

**Comment by whywilson** [comment]
Have you tried reverse the SAK, write it in 0044?

**Comment by the-Jamz** [comment]
> Have you tried reversing the ATQA? write it in 0044?

I have tried this but it yields the error:
`Card doesn't support standard iso14443-3 anticollision`

**Comment by the-Jamz** [comment]
I've now tried emulating the same dump on my proxmark3 and reading with the chameleon, and it does it fine, so seems to be nothing wrong with the dump itself.

**Comment by Foxushka** [comment]
Chumleon FW can't currently emulate 7B UID Mifare Classic cards

**Comment by xianglin1998** [comment]
Caused by mifareclassic crypto1 using wrong uid cascade level.

**Comment by xianglin1998** [comment]
BUG LINE

https://github.com/RfidResearchGroup/ChameleonUltra/blob/8f2d999363249e6e4e7840bba8a59b1213b042ea/firmware/application/src/rfid/nfctag/hf/nfc_mf1.c#L533

**Comment by xianglin1998** [comment]
![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/23152044/471685e1-6fbd-461e-86c5-558c5adcff95)
BUG fixed.

**Comment by the-Jamz** [comment]
Can confirm issue is fixed for me after updating the firmware, thanks!
