### ISSUE TITLE
Checking firmware version?

### ISSUE THREAD

**Issue by grymoire** [RfidResearchGroup/ChameleonUltra#48]
It would be nice to have a feature where we can check the current firmware version number with the latest version of the firmware. This way those who are having trouble compiling the firmware can ensure they have the latest version installed.

**Comment by brianbgarber** [comment]
I was thinking the same thing. I uploaded the latest release of ultra-dfu-app.zip via the chameleonultragui app, but it still shows Firmware Version 1.0.

**Comment by GameTec-live** [comment]
tha automatic firmware versioning was removed because... idk... But it was removed for some reason, so currently all builds are 1.0, yes...

**Comment by grymoire** [comment]
So there is no way to tell if you are up to date or not? 
May I suggest as an enhancement you offer pre-built files with revision numbers (and dates).

**Comment by augustozanellato** [comment]
> 



> tha automatic firmware versioning was removed because... idk... But it was removed for some reason, so currently all builds are 1.0, yes...

It wasn't removed, it just have never been implemented

**Comment by GameTec-live** [comment]
> > tha automatic firmware versioning was removed because... idk... But it was removed for some reason, so currently all builds are 1.0, yes...
> 
> It wasn't removed, it just have never been implemented

there was a commit with remove auto fw versioning or smthng...
