### ISSUE TITLE
[Bug] Slot Nick name starts at 1 not 0

### ISSUE THREAD

**Issue by F9Alejandro** [RfidResearchGroup/ChameleonUltra#51]
Issue:

using command `hw slot nick get -s 1 -st 1` starts at 1 instead of expected 0.

Expected:

Returns slot 1 nickname

Actual:

Returns slot 2 nickname (if it exists)

This happens with all slots. When checking the gui apps it shows slot 2 and above have been named instead of the intended slot 1. Changing the sent slot value from `slot_num` to `int(slot_num-1)` works as expected. Not an ideal solution though. if this could be done firmware side instead this would make it easier and will prevent the need to modify the cli code and add hardcoded values.

Before change:
![CleanShot 2023-08-10 at 21 41 23@2x](https://github.com/RfidResearchGroup/ChameleonUltra/assets/1888010/3ece13e1-4dee-4b47-bc4e-988dccdc402d)

![CleanShot 2023-08-10 at 21 42 32@2x](https://github.com/RfidResearchGroup/ChameleonUltra/assets/1888010/22213d82-027f-4d46-b618-527254e69fc1)

After change:
![CleanShot 2023-08-10 at 21 43 56@2x](https://github.com/RfidResearchGroup/ChameleonUltra/assets/1888010/bc0e1c92-55e7-4438-a61f-3343bbd59d3c)

**Comment by F9Alejandro** [comment]
This needs further investigation. There could be a bug in the way GUI apps grab information from the CU and is causing issues with how data is displayed. (Nick slots could start from 0 instead of the intended 1 based on how the cli works)

**Comment by xianglin1998** [comment]
The chameleon slot offset is from 0 start(in firmware). However, when using a chameleon in practice, it is necessary to map the card slot to the card slot number printed on the hardware.

**Comment by xianglin1998** [comment]
So, this is py CLI bug.

**Comment by F9Alejandro** [comment]
Thank you for the heads up. I know a quick and dirty way to fix it but I believe it would be better to put it as a const enum instead that remaps int 1 to int 0 for nick specific.

**Comment by xianglin1998** [comment]
Slot index decrement
![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/23152044/20f3b3da-68a7-49df-8f20-349edc36df7f)

But slot function lost it.

![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/23152044/dce5b4e9-5ac9-4d74-aaa5-f777d2d68894)

**Comment by F9Alejandro** [comment]
That makes more sense! Thank you for the clarification.

**Comment by xianglin1998** [comment]
Yes, enum type is a strong solution.

**Comment by F9Alejandro** [comment]
Best to use enums for the slot in general if that is the case. It makes it easier to change if the firmware were to make a change to how information is being stored.

**Comment by xianglin1998** [comment]
If I have time, I will refactor it using enumeration types, or if you know how to write PY script, you can push a PR, and the community will be very grateful to you.

**Comment by F9Alejandro** [comment]
I will have to learn how python does their enums. Mainly been using TS, C++, Rust, and Golang. It is possible to make the change. I could also work with szymex73 on getting this working as well. They are currently working on an overhaul to the way how the cli functions with autocomplete and fixes the issue with using any other keys except for left and right arrows making the line messed up.

**Comment by xianglin1998** [comment]
![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/23152044/f55ed624-ede0-466b-b8bf-0ed4bbe976ef)

**Comment by F9Alejandro** [comment]
Please see #52 as this should be able to fix the issue that is happening. I didn't do extensive testing mainly just the 'hw slot nick get' command with '-h' and '-s -st' just to make sure it doesn't crash or do something it shouldn't. Since it will only accept a number 1 - 8 there should be no issue with the conversion from name to value (function should really be called ntov instead of fix now that I think about it)

**Comment by xianglin1998** [comment]
Perfect, i need some time to test all cmd for slot index required. LoL

**Comment by F9Alejandro** [comment]
Closing this as the PR has been merged and I got some valuable insight from @doegox. Thank you again!
