### ISSUE TITLE
Failed, [sdfu] [json.exception.type_error.302] type must be string, but is null

### ISSUE THREAD

**Issue by grymoire** [RfidResearchGroup/ChameleonUltra#53]
I'm getting the following error when I try to load new firmware.
```
 ./flash-dfu-full.sh 
[00:00:00] ------   0% [id:9] Failed, [sdfu] [json.exception.type_error.302] type must be string, but is null
Error: One or more program tasks failed
```

When I built the firmware, this was the report
[build.txt](https://github.com/RfidResearchGroup/ChameleonUltra/files/12322063/build.txt)

**Comment by fmauNeko** [comment]
Had the same issue, solved it by installing https://github.com/NordicSemiconductor/nrf-udev.

**Comment by grymoire** [comment]
That was it. Thanks!

**Comment by doegox** [comment]
now documented
