### ISSUE TITLE
proxmark error to write  MIFARE Classic 1K to ChameleonUltra

### ISSUE THREAD

**Issue by randomk** [RfidResearchGroup/ChameleonUltra#55]
![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/7244439/cd8c3fce-32ed-4569-849d-5abb94eeeada)

Can't set magic card block: 0

**Comment by xianglin1998** [comment]
Default mode is Standard mifareclassic tag, cload can't run on this mode, plz use Chameleon Ultra CLI, run `hf mf eload` to load your dump

**Comment by randomk** [comment]
i want to record MIFARE Classic 1K card in ChameleonUltra using proxmark

**Comment by xianglin1998** [comment]
You should to using `fchk` to check ChamaleonUltra keys and using `restore` to write data for ChameleonUltra by Proxmark3.
![image](https://github.com/RfidResearchGroup/ChameleonUltra/assets/23152044/7eca2038-c515-4b57-8024-55d516c294a9)

**Comment by xianglin1998** [comment]
ChameleonUltra not a `Chinese Magic Card` at default config. You cant write any block using backdoor cmd(Gen1A namely Chinese Magic Card). So `cload` cmd is unavailable.
