### ISSUE TITLE
Can't Detect Low Power 125khz LF tag

### ISSUE THREAD

**Issue by nestharus** [RfidResearchGroup/ChameleonUltra#60]
This is the specific tag

https://thebuilderssupply.com/3millid-3349-3m-fc200-proximity-keyfob-26bit-fac-200

It can't find it

**Comment by doegox** [comment]
Not implemented yet, as many other LF tags, besides EM4100
See https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/Technical_White_Paper.md#low-frequency-reader
