### ISSUE TITLE
When will the MIFARE Classic card number be copied offline?

### ISSUE THREAD

**Issue by fd099** [RfidResearchGroup/ChameleonUltra#62]
For example, click the A button to copy the card number。Thanks！

**Comment by GameTec-live** [comment]
probably not in the next time, because youd need to recovery keys and the nrf processor is just not powerfull enough...
Altough, yes, just copying UID might be possible...

**Comment by Markus-HL** [comment]
only copying UID would be perfect for me. :)

**Comment by fd099** [comment]
> probably not in the next time, because youd need to recovery keys and the nrf processor is just not powerfull enough... Altough, yes, just copying UID might be possible...

The current stage only needs to copy UID would be perfect for me

**Comment by xianglin1998** [comment]
It's very easy to just copy the UID, stay tuned, it won't be long.

**Comment by xianglin1998** [comment]
Implemented At: 7355d512dd2ae480f6a94ca109f4721f91745a94
