### ISSUE TITLE
Attack Information needed!

### ISSUE THREAD

**Issue by derGraph** [RfidResearchGroup/ChameleonUltra#8]
Where can I find any information about the attacks, like how do they work on an firmware level.

Thanks

**Comment by GameTec-live** [comment]
reverse engineer the code, afaik they are performed on the PC:
https://github.com/RfidResearchGroup/ChameleonUltra/tree/main/software/src
https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/software/script/chameleon_cmd.py

**Comment by derGraph** [comment]
I can read code, but I woud like to understand the code im reading!

**Comment by GameTec-live** [comment]
cant help you on that, sorry... (google ig?)

**Comment by xianglin1998** [comment]
# Such as mifareclassic attack:
1、Attack at chameleon firmware side(nonces acquire):
[Acquire](https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/firmware/application/src/rfid/reader/hf/mf1_toolbox.c)
2、Attack at pc side(nonces decrypt):
[Decrypt Algorithm Implement](https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/software/src)
[Decrypt Task Invoke](https://github.com/RfidResearchGroup/ChameleonUltra/blob/main/software/script/chameleon_cli_unit.py)

**Comment by xianglin1998** [comment]
If you want to try to understand its principles, you may need to purchase a Proxmark3 RDV4 to learn RFID knowledge. Believe me, this is a very difficult and interesting process.
