### ISSUE TITLE
Connect to it using ble

### ISSUE THREAD

**Issue by mitmarcus** [RfidResearchGroup/ChameleonUltra#86]
How can I get it to pair/work with the phone?

Thanks in advance

**Comment by GameTec-live** [comment]
you need a app that supports it like Chameleon Ultra GUI (https://github.com/GameTec-live/ChameleonUltraGUI)

**Comment by mitmarcus** [comment]
The app does not see it. Do I need to press something or just waking it up is enough?

**Comment by mitmarcus** [comment]
[Resolved] Phone location must be on

**Comment by foXaCe** [comment]
impossible for me to connect with my android 13 phone
no problem with my android 13 tablet
both are Oppo brand
I tried everything 🤷‍♂️
